//generated by ChatGPT
export function formatDate(
  timestampp: number,
  removeHourAndMinute?: boolean
): string {
  const timestamp = timestampp * 1000; // Convert to milliseconds
  const date = new Date(timestamp);

  const options: Intl.DateTimeFormatOptions = {
    month: "short",
    day: "numeric",
    year: "numeric",
  };

  if (!removeHourAndMinute) {
    options.hour = "2-digit";
    options.minute = "2-digit";
  }

  const formattedDate = date.toLocaleString("en-US", options);
  return formattedDate;
}
