//generated by ChatGPT
export function extractTextUpToFirstComma(inputString: string): string {
  // Define a regular expression to match text up to the first comma
  var regex = /^[^,]*/;

  // Use the match method to find the matched text
  var matches = inputString.match(regex);

  // Check if a match is found
  if (matches && matches.length > 0) {
    // Return the matched text (text up to the first comma)
    return matches[0];
  } else {
    // If no match is found, return an empty string or handle it as needed
    return "";
  }
}
