"use client";

import { NewsProps } from "@/data/types/NewsListProps";
import Image from "next/image";
import Link from "next/link";

import { formatDate } from "../../utils/dateMethods";
import { useCommentsCount } from "../../utils/hooks/useCommentsCount";

const HeroTitle = ({ newsContent }: NewsProps) => {
  const news = newsContent.stories[0];
  const commentCount = useCommentsCount();
  return (
    <div className="w-full lg:w-[710px] pt-8">
      <div className="text-6xl z-[2] font-semibold absolute top-0 drop-shadow-2xl">
        The Edge
      </div>
      <div className="ml-10 ">
        <div className="relative ">
          <div className="relative ">
            <Link
              href={`url-for-content`}
              className="block w-full h-[281px] "
              tabIndex={1}
              aria-hidden
            >
              <Image
                src={news.image || "/no-image.png"}
                fill
                priority
                sizes="(max-width:768px) calc(100vw-60px),(max-width:1024px) 500px,580px"
                alt={news.title}
                className=" object-conrain rounded -z-10 "
              />
            </Link>
          </div>

          <div className="absolute h-[10%] w-full top-0  bg-gradient-to-b from-black/50 to-transparent"></div>
          <div className="absolute h-[10%] w-full bottom-0 bg-gradient-to-t from-black/30 to-transparent"></div>
        </div>
      </div>

      <div className="relative border-b  -top-5 border-gray-31 pb-5">
        <h2
          className={`text-5xl mb-4 font-oswald font-bold leading-[.9] tracking-tight`}
        >
          {news.title}
        </h2>

        <p className=" font-lora mb-4 text-lg leading-5 tracking-[.01rem]">
          {news.autoGeneratedSummary}
        </p>

        <div className=" text-xs tracking-widest flex gap-x-2">
          <div className="uppercase text-franklin">{news.byline}</div>
          <div className="flex text-gray-64">
            <div> {formatDate(news.published)}</div>
            <div className="flex">
              <div className="mx-2 ">|</div>

              <Image src="/message.svg" width={12} height={12} alt="message" />

              <div className="ml-1">{commentCount}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HeroTitle;
