import "./globals.css";
import type { Metadata } from "next";
import { Inter, Oswald, Lora, Kanit } from "next/font/google";

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["700", "600", "400", "500", "300"],
  display: "swap",
  variable: "--font-oswald",
});

const kanit = Kanit({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  display: "swap",
  variable: "--font-kanit",
});

const lora = Lora({
  subsets: ["latin"],
  weight: ["700", "400", "600"],
  display: "swap",
  variable: "--font-lora",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Edge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${oswald.variable} ${lora.variable} ${kanit.variable} dark dark-mode`}
      >
        <div> {children}</div>
      </body>
    </html>
  );
}
